# Generated by Django 2.2.17 on 2020-11-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='is_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
